# Generated by Django 5.1 on 2024-08-29 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dete", models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name="eventmodel",
            name="dates",
        ),
        migrations.AddField(
            model_name="eventmodel",
            name="dates",
            field=models.ManyToManyField(
                related_name="events", to="main_app.eventdate"
            ),
        ),
    ]
